// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtId1grig5i74bMNQJaVYjCqbRCgkDko',
    appId: '1:695880554703:web:ef1f757c16352aa2787fba',
    messagingSenderId: '695880554703',
    projectId: 'flutter-authen-35389',
    authDomain: 'flutter-authen-35389.firebaseapp.com',
    storageBucket: 'flutter-authen-35389.firebasestorage.app',
    measurementId: 'G-MHXJR2GBD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FBIriQpEZkU1_Nd2XGAJE33pNVpw-As',
    appId: '1:695880554703:android:9713c5b25308d5ac787fba',
    messagingSenderId: '695880554703',
    projectId: 'flutter-authen-35389',
    storageBucket: 'flutter-authen-35389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOtfqYZC4NOg3KvfSnW3En3C4F3VJhiQ',
    appId: '1:695880554703:ios:252d15769af175ed787fba',
    messagingSenderId: '695880554703',
    projectId: 'flutter-authen-35389',
    storageBucket: 'flutter-authen-35389.firebasestorage.app',
    iosClientId: '695880554703-ao89g512vtdkrmi7nb785idgv1te4nic.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoOtfqYZC4NOg3KvfSnW3En3C4F3VJhiQ',
    appId: '1:695880554703:ios:252d15769af175ed787fba',
    messagingSenderId: '695880554703',
    projectId: 'flutter-authen-35389',
    storageBucket: 'flutter-authen-35389.firebasestorage.app',
    iosClientId: '695880554703-ao89g512vtdkrmi7nb785idgv1te4nic.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrtId1grig5i74bMNQJaVYjCqbRCgkDko',
    appId: '1:695880554703:web:f75214d19bdf7b14787fba',
    messagingSenderId: '695880554703',
    projectId: 'flutter-authen-35389',
    authDomain: 'flutter-authen-35389.firebaseapp.com',
    storageBucket: 'flutter-authen-35389.firebasestorage.app',
    measurementId: 'G-145EE2W0L9',
  );
}
